import React from "react";
import { VolumeDown, VolumeUp } from "@mui/icons-material";
import { Slider, Stack } from "@mui/material";

function Spotify() {
  const [value, setValue] = React.useState(30);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };
    function handleHover(){
        document.querySelector('.apiLink').style.color='black';
        document.querySelector('.apibefore').style.height='2px';
    }
    function handleHoverOut(){
        document.querySelector('.apiLink').style.color='white';
        document.querySelector('.apibefore').style.height='130%';
    }
  return (
    <div>
      <h3 style={compStyle.title}>
        Now Playing (Probably){" "}
        <button style={compStyle.button}> Refresh</button>
      </h3>

      <div>
        <p style={compStyle.sName}>
          <strong>Elder</strong> - Illusory Motion
        </p>
      </div>

      <div style={compStyle.sPlayer} className="sPlayer">
     
        <Stack spacing={2} direction="row" sx={{ mb: 1 }} alignItems="center">
  <VolumeDown />
  <Slider aria-label="Volume" value={value} onChange={handleChange} />
  <VolumeUp />
</Stack>
      </div>
      <div className="notes">
        <small style={compStyle.sNote} className="sNote">
          * Track generated by the
          <a onMouseOver={handleHover}
            onMouseOut={handleHoverOut}
            className="apiLink"
            style={{ position: "relative", color: "white" }}
            href="https://developer.spotify.com/documentation/web-api"
          >
            <span className="apibefore" style={compStyle.before}></span> Spotify API
          </a>{" "}
          from one of my recent playlists.
        </small>
      </div>
    </div>
  );
}

const compStyle = {
    sPlayer:{
        width:'300px',
        height:'54px',
        // border:'1px solid black',
        // borderRadius: "50px",
        // marginBottom:"10px",
    },
  before: {
    position: "absolute",
    background: "linear-gradient(90deg, rgb(239, 65, 45), rgb(79, 41, 32))",
    height: "130%",
    width: "105%",
    content: "",
    zIndex: -1,
    bottom: "-2px",
    left: "2px",
    transition: "all 0.3s ease 0s",
  },
  sNote: {
    fontSize: "10px",
    textDecoration: "none",
  },
  sName: {
    fontSize: "14px",
    marginBottom:"10px",
  },
  title: {
    fontFamily: '"Exo 2", sans-serif',
    color: "rgb(239, 65, 45)",
    margin: "20.8px 0px",
    textTransform: "uppercase",
    fontSize: "20.8px",
  },
  button: {
    fontFamily: '"Roboto Mono", monospace',
    fontSize: "12px",
    marginLeft: "10px",
    marginTop: "5px",
    border: "1px solid rgb(33, 37, 41)",
    background: "transparent",
    padding: "1px 7px",
    height: "34px",
    cursor: "pointer",
  },
};
export default Spotify;
